### ISSUE TITLE
error TypeError: Object #<Server> has no method 'configure

### ISSUE THREAD

**Issue by mandevx** [steffenwt/nodejs-pub-sub-chat-demo#4]
I have socket.io , redis and all required dependencies installed but on running I get following error 

node app_redis.js 

/root/node_modules/nodejs-pub-sub-chat-demo-master/app_redis.js:22
io.configure( function() {
   ^
TypeError: Object #<Server> has no method 'configure'
    at Object.<anonymous> (/root/node_modules/nodejs-pub-sub-chat-demo-master/app_redis.js:22:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
[root@test nodejs-pub-sub-chat-demo-master]# nano app_redis.js

**Comment by Master244** [comment]
this whole example is not working at all

**Comment by steffenwt** [comment]
Yes... It was created 3 years ago with an older nodejs version. Got no time for an Update but feel free to provide a request to fix it.

**Comment by Master244** [comment]
busy doing that :), will post a request if I get a working example
